sudo: true
language: ruby
rvm: 2.3.1
cache:
  bundler: true
  directories:
  - node_modules
env:
  global:
  - GIT_COMMITTER_NAME='fullvirtue@travis-ci'
  - GIT_COMMITTER_EMAIL='fullvirtue@gmail.com'
  - GIT_AUTHOR_NAME='fullvirtue@travis-ci'
  - GIT_AUTHOR_EMAIL='fullvirtue@gmail.com'
  - secure: "VCeOInn7CTOcGrsuQKmKPI3tpaO+hlL13nNLrjqgqeehWB4E+Y5CIpala7FuxJQuy0CDuxVWpYzg2MQd+RC2I9YGhBML0ose8zIkPoCGiaV45ho3U64iyOeWFDzi1vZ3xZn1eXPNPzNFFVX3N+yR+3/ncRAHXwtsSTYO7dTizYsT1Juud3rWT2zxCc2emHy6S6PL2lLSAhJo3bS/yfmqLLeU/pwE8OB0/eheLz62xBLzQKUlgs7h7BEaaul0hNsQEPP/YhHwiVt46daEllDCi9CfS3Mj+Itk6ts6bXMBkeJ5F49KgrvLZVGM/zNcSCjkvCbwM18dTDwv4imP+eG0wXVtGm45j+wcr9EYbRlSMq5D5VrTpRI2isKbEWXP7IkgbHipD9UudIcmPjkA3+9nP1EROJCsBiCZaJmmHmjEFHSJXDPuJri0W8wS67dWRzRnJnLtRh5qpt1vDGdQ3eQxRRGp+ib1BzXgMj79JQSMD8CqgskpwV2fU0USLSHT6daDsg0XfLvN5RuluFAjvJv8cYUQYYiUfNPDkZ54Gs3ZcANaeaTyQgTITuACMjce/2ZVAQ3YfcDeKq3gVq3lR+M3YuNcpwxnKPw1FEzLVPReOBOSFsGh5r4B4Z97fa8ugrmlQnGrnqo5gcTqXj6NDFLBZkhdrwp6gSAz17rOxlkvDzU="
before_install:
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION"
  - "npm install"
script:
  - git config --global user.name 'fullvirtue@travis-ci'
  - git config --global user.email 'fullvirtue@gmail.com'
  - git remote set-url origin "https://fullvirtue:$GH_TOKEN@github.com/fullvirtue/sendaiitfes2017.git"
  - "bundle exec middleman build --verbose"
  - bundle exec middleman deploy
after_success:
  - |
       $(npm bin)/set-up-ssh --key "$encrypted_c401ae216640_key" \
                             --iv "$encrypted_c401ae216640_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"