sudo: true
language: ruby
rvm: 2.3.1
branches:
  only: master
cache:
  bundler: true
  directories:
  - node_modules
before_install:
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION"
  - "npm install"
script:
  - git config --global user.name 'fullvirtue@travis-ci'
  - git config --global user.email 'fullvirtue@gmail.com'
  - git remote set-url origin "https://fullvirtue:$GH_TOKEN@github.com/fullvirtue/sendaiitfes2017.git"
  - "bundle exec middleman build --verbose"
  - bundle exec middleman deploy
